### ISSUE TITLE
Why use test set to valid model instead of dev set ?

### ISSUE THREAD

**Issue by xfcygaocan** [ZeyuDai/paragraph_implicit_discourse_relations#2]
Is there need a testEpochs ?
https://github.com/ZeyuDai/paragraph_implicit_discourse_relations/blob/b6a0f00c49a3a1d78c4cdba98e1fcf6ce987eb8c/run_discourse_parsing.py#L393

**Comment by ZeyuDai** [comment]
Because all the hyperparameters have been tuned and fixed on dev set.
When I run the code, I will first modify this line to dev set and determined the best hyperparameters combination with grid search.
Finally, I conducted the experiment on test set.

**Comment by xfcygaocan** [comment]
When you get best hyperparameter by grid search, I think you should choose best model by dev set and load best model to test.
https://github.com/ZeyuDai/paragraph_implicit_discourse_relations/blob/b6a0f00c49a3a1d78c4cdba98e1fcf6ce987eb8c/run_discourse_parsing.py#L327
